install: gradle wrapper
language: java
before_deploy: "./gradlew clean build"
deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: $SECRETACCESSKEY
  region: "ap-south-1"
  app: "bsealerts"
  env: "bsealerts-dev"
  zip_file: "build/libs/bse-0.0.1-SNAPSHOT.jar"
  bucket_name: "elasticbeanstalk-ap-south-1-322867968815"
  on:
    branch: master