install: gradle wrapper
language: java
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: $SECRETACCESSKEY
  region: "ap-south-1"
  app: "bsealerts"
  env: "bsealerts-env1"
  bucket_name: "elasticbeanstalk-ap-south-1-241367457943"
  on:
    branch: master